/**
 * Branch-Specific Feature Tests
 *
 * Reads test-results/plugin-manifest.json (generated by scripts/scan-plugin.js)
 * and dynamically generates tests based on what exists in the current branch:
 *   - Every admin page loads without errors
 *   - Every REST endpoint responds (correct HTTP status)
 *   - Feature-specific checks (import/export, AI, schema, etc.)
 */

const { test, expect } = require('@playwright/test');
const { createApiContext, apiGet, apiPost } = require('../fixtures/wp-api');
const fs   = require('fs');
const path = require('path');

const WP_URL      = process.env.WP_URL || 'http://localhost:8080';
const MANIFEST    = path.resolve(__dirname, '../../test-results/plugin-manifest.json');

// ── Load manifest ──────────────────────────────────────────────────────────
let manifest = { adminPages: [], restEndpoints: [], activeFeatures: [], branch: 'unknown' };
try {
  manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
} catch {
  console.warn('[branch-specific] No manifest found — run scripts/scan-plugin.js first');
}

// ── Dynamic admin page tests ───────────────────────────────────────────────
test.describe(`Admin pages — branch: ${manifest.branch}`, () => {
  for (const page_info of manifest.adminPages) {
    test(`${page_info.title} page (${page_info.slug}) loads without errors`, async ({ page }) => {
      const jsErrors = [];
      page.on('console', msg => { if (msg.type() === 'error') jsErrors.push(msg.text()); });
      page.on('pageerror', e => jsErrors.push(e.message));

      const response = await page.goto(`${WP_URL}${page_info.url}`);

      // HTTP level — should not 500
      expect(response.status()).not.toBe(500);

      // Body level — no PHP fatals
      const body = await page.textContent('body');
      expect(body).not.toContain('Fatal error');
      expect(body).not.toContain('Parse error');
      expect(body).not.toContain('WordPress database error');

      // No critical JS errors (allow 3rd-party noise)
      const critical = jsErrors.filter(e =>
        (e.includes('thinkrank') || e.includes('ThinkRank')) &&
        !e.includes('net::ERR_') // ignore network errors for missing API keys
      );
      expect(critical).toHaveLength(0);
    });
  }
});

// ── Dynamic REST endpoint tests ────────────────────────────────────────────
test.describe(`REST API endpoints — branch: ${manifest.branch}`, () => {
  let api;

  test.beforeAll(async () => {
    api = await createApiContext();
  });

  test.afterAll(async () => {
    await api.dispose();
  });

  // Deduplicate paths
  const seen = new Set();
  const uniqueEndpoints = manifest.restEndpoints.filter(ep => {
    const key = `${ep.method}:${ep.apiPath}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  for (const ep of uniqueEndpoints) {
    test(`${ep.method} /thinkrank/v1${ep.apiPath} — endpoint exists`, async () => {
      let resp;
      if (ep.method === 'GET' || ep.method === 'READABLE') {
        resp = await api.get(`/wp-json/thinkrank/v1${ep.apiPath}`);
      } else if (ep.method === 'POST' || ep.method === 'CREATABLE') {
        resp = await api.post(`/wp-json/thinkrank/v1${ep.apiPath}`, { data: {} });
      } else if (ep.method === 'PUT' || ep.method === 'EDITABLE') {
        resp = await api.put(`/wp-json/thinkrank/v1${ep.apiPath}`, { data: {} });
      } else if (ep.method === 'DELETE' || ep.method === 'DELETABLE') {
        resp = await api.delete(`/wp-json/thinkrank/v1${ep.apiPath}`);
      } else {
        resp = await api.get(`/wp-json/thinkrank/v1${ep.apiPath}`);
      }

      // Endpoint should not 404 (not found = route not registered = feature missing)
      // 400 = exists but needs params (OK)
      // 401/403 = exists but auth check (OK)
      // 405 = wrong method (OK, endpoint exists)
      expect(resp.status()).not.toBe(404);

      // Should never return a PHP fatal (that shows as 500 with HTML body)
      if (resp.status() === 500) {
        const body = await resp.text();
        expect(body).not.toContain('Fatal error');
      }
    });
  }
});

// ── Feature-specific tests ─────────────────────────────────────────────────
const features = manifest.activeFeatures || [];

if (features.includes('import')) {
  test.describe('Import/Export feature', () => {
    let api;
    test.beforeAll(async () => { api = await createApiContext(); });
    test.afterAll(async () => { await api.dispose(); });

    test('Import/Export admin page renders', async ({ page }) => {
      await page.goto(`${WP_URL}/wp-admin/admin.php?page=thinkrank-import-export`);
      await page.waitForLoadState('networkidle');
      const body = await page.textContent('body');
      expect(body).not.toContain('Fatal error');
    });
  });
}

if (features.includes('schema')) {
  test.describe('Schema feature', () => {
    let api;
    test.beforeAll(async () => { api = await createApiContext(); });
    test.afterAll(async () => { await api.dispose(); });

    test('Schema endpoint is registered', async () => {
      const resp = await api.get('/wp-json/thinkrank/v1/schema/settings/?post_type=post');
      expect(resp.status()).not.toBe(404);
    });

    test('Homepage has no schema errors in output', async ({ page }) => {
      await page.goto(WP_URL);
      const content = await page.content();
      // If schema JSON-LD is output, it should be valid JSON
      const schemaBlocks = content.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g) || [];
      for (const block of schemaBlocks) {
        const json = block.replace(/<script[^>]*>/, '').replace('</script>', '').trim();
        expect(() => JSON.parse(json)).not.toThrow();
      }
    });
  });
}

if (features.includes('social')) {
  test.describe('Social Meta feature', () => {
    let api;
    test.beforeAll(async () => { api = await createApiContext(); });
    test.afterAll(async () => { await api.dispose(); });

    test('Social media settings endpoint responds', async () => {
      const resp = await api.get('/wp-json/thinkrank/v1/social-media/settings/');
      expect(resp.status()).not.toBe(404);
    });

    test('Homepage has OG meta tags', async ({ page }) => {
      await page.goto(WP_URL);
      // ThinkRank outputs OG tags from frontend/class-seo-manager.php
      const ogTitle = await page.locator('meta[property="og:title"]').getAttribute('content').catch(() => null);
      const ogType  = await page.locator('meta[property="og:type"]').getAttribute('content').catch(() => null);
      // At least og:type should always be present
      expect(ogType).toBeTruthy();
    });
  });
}

if (features.includes('sitemap')) {
  test.describe('Sitemap feature', () => {
    test('Sitemap XML is accessible', async ({ page }) => {
      const resp = await page.goto(`${WP_URL}/wp-sitemap.xml`);
      // 200 = sitemap exists, 404 = disabled/not configured
      expect([200, 404]).toContain(resp.status());
    });
  });
}

if (features.includes('analytics')) {
  test.describe('Analytics feature', () => {
    let api;
    test.beforeAll(async () => { api = await createApiContext(); });
    test.afterAll(async () => { await api.dispose(); });

    test('Integrations settings endpoint responds', async () => {
      const resp = await api.get('/wp-json/thinkrank/v1/integrations/settings/');
      expect([200, 401, 403]).toContain(resp.status());
    });

    test('Test connections endpoint exists', async () => {
      const resp = await api.post('/wp-json/thinkrank/v1/integrations/test-connections/', { data: {} });
      expect(resp.status()).not.toBe(404);
    });
  });
}

if (features.includes('ai')) {
  test.describe('AI Tools feature', () => {
    test('AI Tools admin page renders', async ({ page }) => {
      await page.goto(`${WP_URL}/wp-admin/admin.php?page=thinkrank-ai-tools`);
      await page.waitForLoadState('networkidle');
      const body = await page.textContent('body');
      expect(body).not.toContain('Fatal error');
    });
  });
}

if (features.includes('instant-indexing')) {
  test.describe('Instant Indexing feature', () => {
    let api;
    test.beforeAll(async () => { api = await createApiContext(); });
    test.afterAll(async () => { await api.dispose(); });

    test('Instant indexing settings endpoint is registered', async () => {
      const resp = await api.get('/wp-json/thinkrank/v1/instant-indexing/settings/');
      expect(resp.status()).not.toBe(404);
    });
  });
}
