#!/usr/bin/env php
<?php
/**
 * Auto-generates PHPUnit test stubs for ThinkRank plugin classes.
 *
 * Scans includes/ for PHP class files, extracts class name + public methods,
 * and writes skeleton test files to tests/auto-generated/.
 *
 * Skips classes that already have a hand-written test anywhere in tests/.
 *
 * Usage: php generate-tests.php [plugin-dir]
 */

declare(strict_types=1);

$pluginDir   = rtrim($argv[1] ?? '/var/www/html/wp-content/plugins/thinkrank', '/');
$includesDir = $pluginDir . '/includes';
$testsDir    = $pluginDir . '/tests/auto-generated';

if (!is_dir($includesDir)) {
    fprintf(STDERR, "ERROR: includes/ not found at %s\n", $includesDir);
    exit(1);
}

if (!is_dir($testsDir)) {
    mkdir($testsDir, 0755, true);
    echo "[gen] Created: tests/auto-generated/\n";
}

// Build index of existing test file names (basename only) across all tests/
$existingTests = [];
$testGlob = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($pluginDir . '/tests'));
foreach ($testGlob as $f) {
    if ($f->isFile() && str_ends_with($f->getFilename(), '.php') && str_starts_with($f->getFilename(), 'test-')) {
        $existingTests[$f->getFilename()] = true;
    }
}

// ── Helpers ────────────────────────────────────────────────────────────────

function class_to_test_filename(string $className): string {
    // Yoast_Exporter → test-yoast-exporter.php
    // SEO_Manager    → test-seo-manager.php
    return 'test-' . strtolower(str_replace('_', '-', $className)) . '.php';
}

function extract_php_class_info(string $source): ?array {
    // Namespace
    preg_match('/^namespace\s+([\w\\\\]+)\s*;/m', $source, $ns);
    $namespace = $ns[1] ?? null;

    // Class declaration (skip interfaces and traits)
    if (!preg_match('/^(?:abstract\s+)?class\s+(\w+)/m', $source, $cm)) {
        return null;
    }
    $isAbstract = (bool) preg_match('/^abstract\s+class\s+/m', $source);
    $className  = $cm[1];

    // Public non-magic methods
    preg_match_all('/\bpublic\s+(?:static\s+)?function\s+(\w+)\s*\(/m', $source, $mm);
    $methods = array_filter(
        $mm[1] ?? [],
        fn(string $m): bool => !str_starts_with($m, '__')
    );

    return [
        'namespace'  => $namespace,
        'class'      => $className,
        'abstract'   => $isAbstract,
        'methods'    => array_values($methods),
        'fqcn'       => $namespace ? '\\' . $namespace . '\\' . $className : '\\' . $className,
    ];
}

function generate_test_content(array $info, string $testFilename): string {
    $testNamespace = 'ThinkRank\\Tests\\AutoGenerated';
    $testClass     = 'Test_' . $info['class'];
    $fqcn          = $info['fqcn'];
    $sourceClass   = $info['class'];
    $generated     = gmdate('Y-m-d');

    // Build per-method stubs
    $methodStubs = '';
    if (!empty($info['methods'])) {
        foreach ($info['methods'] as $method) {
            $methodStubs .= <<<PHP

    public function test_{$method}_exists(): void {
        \$this->assertTrue(
            method_exists({$sourceClass}::class, '{$method}'),
            '{$sourceClass}::{$method}() should exist'
        );
    }

PHP;
        }
    } else {
        $methodStubs = <<<PHP

    public function test_class_is_instantiable(): void {
        \$this->markTestIncomplete(
            '{$sourceClass} has no public non-magic methods to test automatically.'
        );
    }

PHP;
    }

    $constructorNote = $info['abstract']
        ? '// NOTE: This is an abstract class — test via a concrete subclass.'
        : '// NOTE: Constructor may require arguments. Adjust setUp() as needed.';

    $setupBlock = $info['abstract']
        ? ''
        : <<<PHP

    protected function setUp(): void {
        parent::setUp();
        // TODO: Instantiate {$sourceClass} here if the constructor allows it
        // \$this->subject = new {$sourceClass}();
    }

PHP;

    return <<<PHP
<?php

/**
 * Auto-generated test stubs for {$sourceClass}
 *
 * Generated: {$generated}
 * Source FQCN: {$fqcn}
 *
 * @package ThinkRank\\Tests\\AutoGenerated
 *
 * HOW TO USE:
 *   1. Replace markTestIncomplete() calls with real assertions.
 *   2. Move completed tests to tests/importers/ (or a feature-specific subdir)
 *      and remove this file so it is not regenerated.
 */

declare(strict_types=1);

namespace {$testNamespace};

use PHPUnit\\Framework\\TestCase;

{$constructorNote}
/**
 * @covers {$fqcn}
 */
class {$testClass} extends TestCase {{$setupBlock}{$methodStubs}}
PHP;
}

// ── Main scan ──────────────────────────────────────────────────────────────

$files     = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($includesDir));
$generated = 0;
$skipped   = 0;
$total     = 0;

foreach ($files as $file) {
    if (!$file->isFile()) continue;
    if ($file->getExtension() !== 'php') continue;
    if ($file->getFilename() === 'index.php') continue;

    $source = file_get_contents($file->getPathname());
    $info   = extract_php_class_info($source);

    if (!$info) continue;
    $total++;

    $testFilename = class_to_test_filename($info['class']);

    // Skip if a hand-written test already exists
    if (isset($existingTests[$testFilename])) {
        $skipped++;
        continue;
    }

    $destPath = $testsDir . '/' . $testFilename;

    // Skip if auto-generated test already exists (don't overwrite)
    if (file_exists($destPath)) {
        $skipped++;
        continue;
    }

    $content = generate_test_content($info, $testFilename);
    file_put_contents($destPath, $content);
    $generated++;

    $relPath = 'tests/auto-generated/' . $testFilename;
    echo "[gen] + {$relPath}  ({$info['class']})\n";
}

echo "\n[gen] Scanned {$total} classes — generated {$generated}, skipped {$skipped} (already have tests)\n";
